name: Java CI with Gradle (Forge 1.7.10 - draft release)

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags: 'v*1.7.10' # Push events to matching v*+1.7.10

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up JDK 6 & 8
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: |
          6
          8
    - name: Install advancecomp
      run: sudo apt-get install advancecomp
    - name: Install strip-nondeterminism
      run: sudo apt-get install strip-nondeterminism
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1
    - name: Build with Gradle
      env:
        BUILD_RELEASE: ${{ github.event.release.prerelease == false }}
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: wrapper
        cache-disabled: true
        arguments: SetupCIWorkspace build --stacktrace --warning-mode all
    - name: Run strip-nondeterminism on built .jar files
      run: strip-nondeterminism build/libs/*.jar
    - name: Run advzip (-i 99999) on built .jar files
      run: advzip --shrink-insane -kzi 99999 -p build/libs/*.jar
    - name: Draft release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref }}
        name: Draft release ${{ github.ref }}
        body: Replace this text with the description of this release!
        draft: true
        prerelease: false
        files: build/libs/*.jar
