name: Java CI with Gradle (Forge 1.7.10 - draft release)

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags: 'v*1.7.10' # Push events to matching v*+1.7.10

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up JDK 6
      id: setup_jdk_6
      uses: actions/setup-java@v1
      with:
        java-version: 6
    - name: Set up JDK 8
      id: setup_jdk_8
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Install advancecomp
      run: sudo apt-get install advancecomp
    - name: Install strip-nondeterminism
      run: sudo apt-get install strip-nondeterminism
    - name: Print Java enviromental variables for debugging purposes.
      run: |
        set | grep JAVA
        echo JDK 6 installated path should be ${{ steps.setup_jdk_6.outputs.path }}
    - name: Build with Gradle
      env:
        GITHUB_ACTIONS_JDK_6: ${{ steps.setup_jdk_6.outputs.path }}
        BUILD_RELEASE: ${{ github.event.release.prerelease == false }}
      uses: eskatos/gradle-command-action@v1
      with:
        gradle-version: wrapper
        wrapper-cache-enabled: false
        dependencies-cache-enabled: false
        configuration-cache-enabled: false
        arguments: SetupCIWorkspace build
    - name: Run strip-nondeterminism on built .jar files
      run: strip-nondeterminism build/libs/*.jar
    - name: Run advzip (-i 99999) on built .jar files
      run: advzip --shrink-insane -kzi 99999 -p build/libs/*.jar
    - name: Draft release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Draft release ${{ github.ref }}
        body: Replace this text with the description of this release!
        draft: true
        prerelease: false
    - name: Upload draft release assets
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/libs/*.jar
