name: Java CI with Gradle (Forge 1.7.10 - snaphot)

on:
  push:
    branches:
      - forge-1.7.10
  pull_request:
    branches:
      - forge-1.7.10

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up JDK 6 & 8
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: |
          6
          8
    - name: Install advancecomp
      run: sudo apt-get install advancecomp
    - name: Install strip-nondeterminism
      run: sudo apt-get install strip-nondeterminism
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: wrapper
        cache-read-only: ${{ github.ref != 'refs/heads/forge-1.7.10' }}
        arguments: SetupCIWorkspace build --stacktrace --warning-mode all
    - name: Run strip-nondeterminism on built .jar files
      run: strip-nondeterminism build/libs/*.jar
    - name: Run advzip (-i 999) on built .jar files
      run: advzip --shrink-insane -kzi 999 -p build/libs/*.jar
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Package
        path: build/libs
